apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # first install ESO CRDs then use them
    helm.sh/hook: post-install,post-upgrade
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterSecretStore.clusterLocation }}
          clusterName: {{ .Values.clusterSecretStore.clusterName }}
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.serviceAccountName }}
            namespace: {{ .Release.Namespace }}
